// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnaddrlaoerkbyciifcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuYWRkcmxhb2Vya2J5Y2lpZmNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTA1ODgsImV4cCI6MjA3MDY2NjU4OH0.BGuNRKkaMt4gQJJlK1fcTTcX7hmSPVjfqucK30qE400";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});